export const PLANT_LIST_REQUEST = 'PLANT_LIST_REQUEST'
export const PLANT_LIST_SUCCESS = 'PLANT_LIST_SUCCESS'
export const PLANT_LIST_FAIL = 'PLANT_LIST_FAIL'
export const PLANT_LIST_RESET = 'PLANT_LIST_RESET'

export const PLANT_DETAILS_REQUEST = 'PLANT_DETAILS_REQUEST'
export const PLANT_DETAILS_SUCCESS = 'PLANT_DETAILS_SUCCESS'  
export const PLANT_DETAILS_FAIL = 'PLANT_DETAILS_FAIL'
export const PLANT_DETAILS_RESET = 'PLANT_DETAILS_RESET'

export const PLANT_CREATE_REQUEST = 'PLANT_CREATE_REQUEST'
export const PLANT_CREATE_SUCCESS = 'PLANT_CREATE_SUCCESS'  
export const PLANT_CREATE_FAIL = 'PLANT_CREATE_FAIL'

export const PLANT_DELETE_REQUEST = 'PLANT_DELETE_REQUEST'
export const PLANT_DELETE_SUCCESS = 'PLANT_DELETE_SUCCESS'  
export const PLANT_DELETE_FAIL = 'PLANT_DELETE_FAIL'
